import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Header2 from '../components/Header';
import { NextPage } from 'next';
import Links from '../components/Links';
import Journey from '../components/Journey';
import Projects from '../components/Projects';
import Contacts from '../components/Contacts';
import {Section,SectionsContainer,Navbar,Header} from "react-fullpage";

export default function Home() {
  let options = {
    anchors:              ['Home', 'Journey', 'Projects', 'Contacts'],
    scrollBar:            false,
    navigation:           true,
    verticalAlign:        false,
    sectionPaddingTop:    '50px',
    sectionPaddingBottom: '50px',
    arrowNavigation:      true
  };
  return (
    <div className={styles.container} >
      <Head>
        <title>Muhire Ighor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className='bg-[#092027]'>
  <Section>
    <Header2 />
  </Section>
  <SectionsContainer {...options}>
    <Section>
<Links key={1}/>
    </Section>
    <Section>
    <Journey key={2} />
    </Section>
    <Section>
<Projects key={3} />
    </Section>
    <Section>
<Contacts key={4}/>
    </Section>
  </SectionsContainer>


    
</div>


    </div>
  )
}
